-- config 模块已并入 core（由 core 单一 DLL 编译导出）。
-- 其接口单元（silicon.config / silicon.config.*）、实现单元（src/**.cpp）
-- 现统一在 core/xmake.lua 内处理；本模块不再生成 :config 分区（版本信息由
-- silicon.core::GetVersion* 统一提供）。故本文件不再声明任何 target。
-- 消费方直接 add_deps("core") 即可 import silicon.config。
