-- event 模块已并入 core（由 core 单一 DLL 编译导出）。
-- 其接口单元（silicon.event / silicon.event.error）、实现单元（src/event.cpp）
-- 与 :config 分区生成（event.config.cppm.in）现统一在 core/xmake.lua 内处理，
-- 故本文件不再声明任何 target。消费方直接 add_deps("core") 即可 import silicon.event。
