#pragma once

#include "silicon/coroutine/concepts/awaitable.hpp"
#include "silicon/coroutine/concepts/buffer.hpp"
#include "silicon/coroutine/concepts/executor.hpp"
#include "silicon/coroutine/concepts/promise.hpp"
#include "silicon/coroutine/concepts/range_of.hpp"
#include "silicon/coroutine/expected.hpp"

#ifdef LIBCORO_FEATURE_NETWORKING
#    include "silicon/coroutine/net/dns/resolver.hpp"
#    include "silicon/coroutine/net/tcp/client.hpp"
#    include "silicon/coroutine/net/tcp/server.hpp"
#    include "silicon/coroutine/poll.hpp"
#    include "silicon/coroutine/scheduler.hpp"
#    ifdef LIBCORO_FEATURE_TLS
#        include "silicon/coroutine/net/tls/client.hpp"
#        include "silicon/coroutine/net/tls/connection_status.hpp"
#        include "silicon/coroutine/net/tls/context.hpp"
#        include "silicon/coroutine/net/tls/server.hpp"
#    endif
#    include "silicon/coroutine/net/connect.hpp"
#    include "silicon/coroutine/net/hostname.hpp"
#    include "silicon/coroutine/net/io_status.hpp"
#    include "silicon/coroutine/net/ip_address.hpp"
#    include "silicon/coroutine/net/recv_status.hpp"
#    include "silicon/coroutine/net/send_status.hpp"
#    include "silicon/coroutine/net/socket.hpp"
#    include "silicon/coroutine/net/udp/peer.hpp"
#endif

#include "silicon/coroutine/condition_variable.hpp"
#include "silicon/coroutine/default_executor.hpp"
#include "silicon/coroutine/event.hpp"
#include "silicon/coroutine/generator.hpp"
#include "silicon/coroutine/invoke.hpp"
#include "silicon/coroutine/latch.hpp"
#include "silicon/coroutine/mutex.hpp"
#include "silicon/coroutine/queue.hpp"
#include "silicon/coroutine/ring_buffer.hpp"
#include "silicon/coroutine/semaphore.hpp"
#include "silicon/coroutine/shared_mutex.hpp"
#include "silicon/coroutine/sync_wait.hpp"
#include "silicon/coroutine/task.hpp"
#include "silicon/coroutine/task_container.hpp"
#include "silicon/coroutine/task_group.hpp"
#include "silicon/coroutine/pool.hpp"
#include "silicon/coroutine/time.hpp"
#include "silicon/coroutine/when_all.hpp"
#include "silicon/coroutine/when_any.hpp"
