-- di 模块已并入 core（由 core 单一 DLL 编译导出）。
-- 其接口单元（silicon.di / silicon.di:facade / silicon.di.error）与 :config 分区
-- 生成（di.config.cppm.in）现统一在 core/xmake.lua 内处理，故本文件不再声明
-- 任何 target。消费方直接 add_deps("core") 即可 import silicon.di。
