




#define SFFI_IA64_TYPE_SMALL_STRUCT (SFFI_TYPE_LAST + 1)


#define SFFI_IA64_TYPE_HFA_FLOAT (SFFI_TYPE_LAST + 2)
#define SFFI_IA64_TYPE_HFA_DOUBLE (SFFI_TYPE_LAST + 3)
#define SFFI_IA64_TYPE_HFA_LDOUBLE (SFFI_TYPE_LAST + 4)
