-- logger 模块已并入 core（由 core 单一 DLL 编译导出）。
-- 其接口单元（silicon.logger / silicon.logger.error）、实现单元（src/**.cpp）、
-- spdlog 依赖现统一在 core/xmake.lua 内处理；本模块不再生成 :config 分区
-- （版本信息由 silicon.core::GetVersion* 统一提供）。故本文件不再声明任何
-- target。消费方直接 add_deps("core") 即可 import silicon.logger
-- （spdlog 头文件经 core 的 public packages 向下传递）。
